name: Build CLI for Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v6

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' app/pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build_cli:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            suffix: linux-x86-64
          - runner: ubuntu-22.04-arm
            suffix: linux-arm-64
    runs-on: ${{ matrix.runner }}
    container: debian:10

    steps:
      - name: Install build dependencies
        run: |
          sed -i \
            -e 's|deb.debian.org|archive.debian.org|g' \
            -e '/security.debian.org/d' \
            /etc/apt/sources.list
          apt-get -o Acquire::Check-Valid-Until=false update
          apt-get install -y --no-install-recommends \
            build-essential ca-certificates curl git libssl-dev pkg-config

      - uses: actions/checkout@v6

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
            | sh -s -- -y --profile minimal --default-toolchain none
          . "$HOME/.cargo/env"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          rustup toolchain install # version from rust-toolchain.toml

      - name: Compile CLI
        run: cargo build --release --package localsend-cli

      - name: Create tar.gz archive
        run: tar -czvf LocalSend-CLI-${{ needs.build.outputs.version }}-${{ matrix.suffix }}.tar.gz -C target/release localsend-cli

      - name: Upload CLI
        uses: actions/upload-artifact@v6
        with:
          name: cli-${{ matrix.suffix }}-result
          path: LocalSend-CLI-${{ needs.build.outputs.version }}-${{ matrix.suffix }}.tar.gz
          if-no-files-found: error
